/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2ChainShape
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "Box2D/Collision/Shapes/b2ChainShape.h"


/** Set attributes (key, value)
 * 
 */
static int b2ChainShape__set_(lua_State *L) {

  b2ChainShape *self = *((b2ChainShape **)dub_checksdata_n(L, 1, "b2.ChainShape"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub_hash(key, 19);
  switch(key_h) {
    case 9: {
      if (DUB_ASSERT_KEY(key, "m_vertices")) break;
      dub_protect(L, 1, 3, "m_vertices");
      self->m_vertices = *((b2Vec2 **)dub_checksdata_n(L, 3, "b2.Vec2"));
      return 0;
    }
    case 14: {
      if (DUB_ASSERT_KEY(key, "m_count")) break;
      self->m_count = luaL_checkint(L, 3);
      return 0;
    }
    case 5: {
      if (DUB_ASSERT_KEY(key, "m_prevVertex")) break;
      self->m_prevVertex = **((b2Vec2 **)dub_checksdata_n(L, 3, "b2.Vec2"));
      return 0;
    }
    case 3: {
      if (DUB_ASSERT_KEY(key, "m_nextVertex")) break;
      self->m_nextVertex = **((b2Vec2 **)dub_checksdata_n(L, 3, "b2.Vec2"));
      return 0;
    }
    case 2: {
      if (DUB_ASSERT_KEY(key, "m_hasPrevVertex")) break;
      self->m_hasPrevVertex = luaL_checkboolean(L, 3);
      return 0;
    }
    case 13: {
      if (DUB_ASSERT_KEY(key, "m_hasNextVertex")) break;
      self->m_hasNextVertex = luaL_checkboolean(L, 3);
      return 0;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "m_type")) break;
      self->m_type = (b2Shape::Type)luaL_checkint(L, 3);
      return 0;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "m_radius")) break;
      self->m_radius = luaL_checknumber(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2ChainShape__get_(lua_State *L) {

  b2ChainShape *self = *((b2ChainShape **)dub_checksdata_n(L, 1, "b2.ChainShape", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub_hash(key, 19);
  switch(key_h) {
    case 9: {
      if (DUB_ASSERT_KEY(key, "m_vertices")) break;
      b2Vec2 *retval__ = self->m_vertices;
      if (!retval__) return 0;
      dub_pushudata(L, retval__, "b2.Vec2", false);
      return 1;
    }
    case 14: {
      if (DUB_ASSERT_KEY(key, "m_count")) break;
      lua_pushnumber(L, self->m_count);
      return 1;
    }
    case 5: {
      if (DUB_ASSERT_KEY(key, "m_prevVertex")) break;
      dub_pushudata(L, &self->m_prevVertex, "b2.Vec2", false);
      return 1;
    }
    case 3: {
      if (DUB_ASSERT_KEY(key, "m_nextVertex")) break;
      dub_pushudata(L, &self->m_nextVertex, "b2.Vec2", false);
      return 1;
    }
    case 2: {
      if (DUB_ASSERT_KEY(key, "m_hasPrevVertex")) break;
      lua_pushboolean(L, self->m_hasPrevVertex);
      return 1;
    }
    case 13: {
      if (DUB_ASSERT_KEY(key, "m_hasNextVertex")) break;
      lua_pushboolean(L, self->m_hasNextVertex);
      return 1;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "m_type")) break;
      lua_pushnumber(L, self->m_type);
      return 1;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "m_radius")) break;
      lua_pushnumber(L, self->m_radius);
      return 1;
    }
  }
  return 0;
}

/** Cast (class_name)
 * 
 */
static int b2ChainShape__cast_(lua_State *L) {

  b2ChainShape *self = *((b2ChainShape **)dub_checksdata_n(L, 1, "b2.ChainShape"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "b2.Shape")) break;
      *retval__ = static_cast<b2Shape *>(self);
      return 1;
    }
  }
  return 0;
}

/** b2ChainShape::b2ChainShape()
 * vendor/Box2D/Box2D/Collision/Shapes/b2ChainShape.h:35
 */
static int b2ChainShape_b2ChainShape(lua_State *L) {
  try {
    b2ChainShape *retval__ = new b2ChainShape();
    dub_pushudata(L, retval__, "b2.ChainShape", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "b2ChainShape: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "b2ChainShape: Unknown exception");
  }
  return dub_error(L);
}

/** b2ChainShape::~b2ChainShape()
 * vendor/Box2D/Box2D/Collision/Shapes/b2ChainShape.h:38
 */
static int b2ChainShape__b2ChainShape(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "b2.ChainShape"));
    if (userdata->gc) {
      b2ChainShape *self = (b2ChainShape *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "~b2ChainShape: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "~b2ChainShape: Unknown exception");
  }
  return dub_error(L);
}

/** void b2ChainShape::CreateLoop(const b2Vec2 *vertices, int32 count)
 * vendor/Box2D/Box2D/Collision/Shapes/b2ChainShape.h:43
 */
static int b2ChainShape_CreateLoop(lua_State *L) {
  try {
    b2ChainShape *self = *((b2ChainShape **)dub_checksdata(L, 1, "b2.ChainShape"));
    b2Vec2 *vertices = *((b2Vec2 **)dub_checksdata(L, 2, "b2.Vec2"));
    int32 count = dub_checkint(L, 3);
    self->CreateLoop(vertices, count);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "CreateLoop: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "CreateLoop: Unknown exception");
  }
  return dub_error(L);
}

/** void b2ChainShape::CreateChain(const b2Vec2 *vertices, int32 count)
 * vendor/Box2D/Box2D/Collision/Shapes/b2ChainShape.h:48
 */
static int b2ChainShape_CreateChain(lua_State *L) {
  try {
    b2ChainShape *self = *((b2ChainShape **)dub_checksdata(L, 1, "b2.ChainShape"));
    b2Vec2 *vertices = *((b2Vec2 **)dub_checksdata(L, 2, "b2.Vec2"));
    int32 count = dub_checkint(L, 3);
    self->CreateChain(vertices, count);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "CreateChain: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "CreateChain: Unknown exception");
  }
  return dub_error(L);
}

/** void b2ChainShape::SetPrevVertex(const b2Vec2 &prevVertex)
 * vendor/Box2D/Box2D/Collision/Shapes/b2ChainShape.h:52
 */
static int b2ChainShape_SetPrevVertex(lua_State *L) {
  try {
    b2ChainShape *self = *((b2ChainShape **)dub_checksdata(L, 1, "b2.ChainShape"));
    b2Vec2 *prevVertex = *((b2Vec2 **)dub_checksdata(L, 2, "b2.Vec2"));
    self->SetPrevVertex(*prevVertex);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "SetPrevVertex: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SetPrevVertex: Unknown exception");
  }
  return dub_error(L);
}

/** void b2ChainShape::SetNextVertex(const b2Vec2 &nextVertex)
 * vendor/Box2D/Box2D/Collision/Shapes/b2ChainShape.h:56
 */
static int b2ChainShape_SetNextVertex(lua_State *L) {
  try {
    b2ChainShape *self = *((b2ChainShape **)dub_checksdata(L, 1, "b2.ChainShape"));
    b2Vec2 *nextVertex = *((b2Vec2 **)dub_checksdata(L, 2, "b2.Vec2"));
    self->SetNextVertex(*nextVertex);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "SetNextVertex: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SetNextVertex: Unknown exception");
  }
  return dub_error(L);
}

/** b2Shape * b2ChainShape::Clone(b2BlockAllocator *allocator) const
 * vendor/Box2D/Box2D/Collision/Shapes/b2ChainShape.h:59
 */
static int b2ChainShape_Clone(lua_State *L) {
  try {
    b2ChainShape *self = *((b2ChainShape **)dub_checksdata(L, 1, "b2.ChainShape"));
    b2BlockAllocator *allocator = *((b2BlockAllocator **)dub_checksdata(L, 2, "b2.BlockAllocator"));
    b2Shape *retval__ = self->Clone(allocator);
    if (!retval__) return 0;
    dub_pushudata(L, retval__, "b2.Shape", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "Clone: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Clone: Unknown exception");
  }
  return dub_error(L);
}

/** int32 b2ChainShape::GetChildCount() const
 * vendor/Box2D/Box2D/Collision/Shapes/b2ChainShape.h:62
 */
static int b2ChainShape_GetChildCount(lua_State *L) {
  try {
    b2ChainShape *self = *((b2ChainShape **)dub_checksdata(L, 1, "b2.ChainShape"));
    lua_pushnumber(L, self->GetChildCount());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetChildCount: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetChildCount: Unknown exception");
  }
  return dub_error(L);
}

/** void b2ChainShape::GetChildEdge(b2EdgeShape *edge, int32 index) const
 * vendor/Box2D/Box2D/Collision/Shapes/b2ChainShape.h:65
 */
static int b2ChainShape_GetChildEdge(lua_State *L) {
  try {
    b2ChainShape *self = *((b2ChainShape **)dub_checksdata(L, 1, "b2.ChainShape"));
    b2EdgeShape *edge = *((b2EdgeShape **)dub_checksdata(L, 2, "b2.EdgeShape"));
    int32 index = dub_checkint(L, 3);
    self->GetChildEdge(edge, index);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetChildEdge: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetChildEdge: Unknown exception");
  }
  return dub_error(L);
}

/** bool b2ChainShape::TestPoint(const b2Transform &transform, const b2Vec2 &p) const
 * vendor/Box2D/Box2D/Collision/Shapes/b2ChainShape.h:69
 */
static int b2ChainShape_TestPoint(lua_State *L) {
  try {
    b2ChainShape *self = *((b2ChainShape **)dub_checksdata(L, 1, "b2.ChainShape"));
    b2Transform *transform = *((b2Transform **)dub_checksdata(L, 2, "b2.Transform"));
    b2Vec2 *p = *((b2Vec2 **)dub_checksdata(L, 3, "b2.Vec2"));
    lua_pushboolean(L, self->TestPoint(*transform, *p));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "TestPoint: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "TestPoint: Unknown exception");
  }
  return dub_error(L);
}

/** bool b2ChainShape::RayCast(b2RayCastOutput *output, const b2RayCastInput &input, const b2Transform &transform, int32 childIndex) const
 * vendor/Box2D/Box2D/Collision/Shapes/b2ChainShape.h:73
 */
static int b2ChainShape_RayCast(lua_State *L) {
  try {
    b2ChainShape *self = *((b2ChainShape **)dub_checksdata(L, 1, "b2.ChainShape"));
    b2RayCastOutput *output = *((b2RayCastOutput **)dub_checksdata(L, 2, "b2.RayCastOutput"));
    b2RayCastInput *input = *((b2RayCastInput **)dub_checksdata(L, 3, "b2.RayCastInput"));
    b2Transform *transform = *((b2Transform **)dub_checksdata(L, 4, "b2.Transform"));
    int32 childIndex = dub_checkint(L, 5);
    lua_pushboolean(L, self->RayCast(output, *input, *transform, childIndex));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "RayCast: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "RayCast: Unknown exception");
  }
  return dub_error(L);
}

/** void b2ChainShape::ComputeAABB(b2AABB *aabb, const b2Transform &transform, int32 childIndex) const
 * vendor/Box2D/Box2D/Collision/Shapes/b2ChainShape.h:76
 */
static int b2ChainShape_ComputeAABB(lua_State *L) {
  try {
    b2ChainShape *self = *((b2ChainShape **)dub_checksdata(L, 1, "b2.ChainShape"));
    b2AABB *aabb = *((b2AABB **)dub_checksdata(L, 2, "b2.AABB"));
    b2Transform *transform = *((b2Transform **)dub_checksdata(L, 3, "b2.Transform"));
    int32 childIndex = dub_checkint(L, 4);
    self->ComputeAABB(aabb, *transform, childIndex);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "ComputeAABB: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "ComputeAABB: Unknown exception");
  }
  return dub_error(L);
}

/** void b2ChainShape::ComputeMass(b2MassData *massData, float32 density) const
 * vendor/Box2D/Box2D/Collision/Shapes/b2ChainShape.h:80
 */
static int b2ChainShape_ComputeMass(lua_State *L) {
  try {
    b2ChainShape *self = *((b2ChainShape **)dub_checksdata(L, 1, "b2.ChainShape"));
    b2MassData *massData = *((b2MassData **)dub_checksdata(L, 2, "b2.MassData"));
    float32 density = dub_checknumber(L, 3);
    self->ComputeMass(massData, density);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "ComputeMass: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "ComputeMass: Unknown exception");
  }
  return dub_error(L);
}

/** b2Shape::Type b2Shape::GetType() const
 * vendor/Box2D/Box2D/Collision/Shapes/b2Shape.h:62
 */
static int b2ChainShape_GetType(lua_State *L) {
  try {
    b2ChainShape *self = *((b2ChainShape **)dub_checksdata(L, 1, "b2.ChainShape"));
    lua_pushnumber(L, self->GetType());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetType: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetType: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int b2ChainShape___tostring(lua_State *L) {
  b2ChainShape *self = *((b2ChainShape **)dub_checksdata_n(L, 1, "b2.ChainShape"));
  lua_pushfstring(L, "b2.ChainShape: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2ChainShape_member_methods[] = {
  { "__newindex"   , b2ChainShape__set_   },
  { "__index"      , b2ChainShape__get_   },
  { "_cast_"       , b2ChainShape__cast_  },
  { "new"          , b2ChainShape_b2ChainShape },
  { "__gc"         , b2ChainShape__b2ChainShape },
  { "CreateLoop"   , b2ChainShape_CreateLoop },
  { "CreateChain"  , b2ChainShape_CreateChain },
  { "SetPrevVertex", b2ChainShape_SetPrevVertex },
  { "SetNextVertex", b2ChainShape_SetNextVertex },
  { "Clone"        , b2ChainShape_Clone   },
  { "GetChildCount", b2ChainShape_GetChildCount },
  { "GetChildEdge" , b2ChainShape_GetChildEdge },
  { "TestPoint"    , b2ChainShape_TestPoint },
  { "RayCast"      , b2ChainShape_RayCast },
  { "ComputeAABB"  , b2ChainShape_ComputeAABB },
  { "ComputeMass"  , b2ChainShape_ComputeMass },
  { "GetType"      , b2ChainShape_GetType },
  { "__tostring"   , b2ChainShape___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_b2_ChainShape(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.ChainShape");
  // <mt>

  // register member methods
  luaL_register(L, NULL, b2ChainShape_member_methods);
  // save meta-table in b2
  dub_register(L, "b2", "ChainShape", "ChainShape");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
