/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2Jacobian
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "Box2D/Dynamics/Joints/b2Joint.h"


/** Set attributes (key, value)
 * 
 */
static int b2Jacobian__set_(lua_State *L) {

  b2Jacobian *self = *((b2Jacobian **)dub_checksdata_n(L, 1, "b2.Jacobian"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub_hash(key, 4);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "linear")) break;
      self->linear = **((b2Vec2 **)dub_checksdata_n(L, 3, "b2.Vec2"));
      return 0;
    }
    case 3: {
      if (DUB_ASSERT_KEY(key, "angularA")) break;
      self->angularA = luaL_checknumber(L, 3);
      return 0;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "angularB")) break;
      self->angularB = luaL_checknumber(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2Jacobian__get_(lua_State *L) {

  b2Jacobian *self = *((b2Jacobian **)dub_checksdata_n(L, 1, "b2.Jacobian", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub_hash(key, 4);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "linear")) break;
      dub_pushudata(L, &self->linear, "b2.Vec2", false);
      return 1;
    }
    case 3: {
      if (DUB_ASSERT_KEY(key, "angularA")) break;
      lua_pushnumber(L, self->angularA);
      return 1;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "angularB")) break;
      lua_pushnumber(L, self->angularB);
      return 1;
    }
  }
  return 0;
}

/** b2Jacobian()
 * 
 */
static int b2Jacobian_b2Jacobian(lua_State *L) {
  try {
    b2Jacobian *retval__ = new b2Jacobian();
    dub_pushudata(L, retval__, "b2.Jacobian", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "b2Jacobian: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "b2Jacobian: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int b2Jacobian___tostring(lua_State *L) {
  b2Jacobian *self = *((b2Jacobian **)dub_checksdata_n(L, 1, "b2.Jacobian"));
  lua_pushfstring(L, "b2.Jacobian: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2Jacobian_member_methods[] = {
  { "__newindex"   , b2Jacobian__set_     },
  { "__index"      , b2Jacobian__get_     },
  { "new"          , b2Jacobian_b2Jacobian },
  { "__tostring"   , b2Jacobian___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_b2_Jacobian(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.Jacobian");
  // <mt>

  // register member methods
  luaL_register(L, NULL, b2Jacobian_member_methods);
  // save meta-table in b2
  dub_register(L, "b2", "Jacobian", "Jacobian");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
