/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2JointDef
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "Box2D/Dynamics/Joints/b2Joint.h"


/** ~b2JointDef()
 * 
 */
static int b2JointDef__b2JointDef(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "b2.JointDef"));
    if (userdata->gc) {
      b2JointDef *self = (b2JointDef *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "~b2JointDef: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "~b2JointDef: Unknown exception");
  }
  return dub_error(L);
}

/** Set attributes (key, value)
 * 
 */
static int b2JointDef__set_(lua_State *L) {

  b2JointDef *self = *((b2JointDef **)dub_checksdata_n(L, 1, "b2.JointDef"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub_hash(key, 7);
  switch(key_h) {
    case 3: {
      if (DUB_ASSERT_KEY(key, "type")) break;
      self->type = (b2JointType)luaL_checkint(L, 3);
      return 0;
    }
    case 2: {
      if (DUB_ASSERT_KEY(key, "userData")) break;
      dub_protect(L, 1, 3, "userData");
      self->userData = *((void **)dub_checksdata_n(L, 3, "void"));
      return 0;
    }
    case 4: {
      if (DUB_ASSERT_KEY(key, "bodyA")) break;
      dub_protect(L, 1, 3, "bodyA");
      self->bodyA = *((b2Body **)dub_checksdata_n(L, 3, "b2.Body"));
      return 0;
    }
    case 5: {
      if (DUB_ASSERT_KEY(key, "bodyB")) break;
      dub_protect(L, 1, 3, "bodyB");
      self->bodyB = *((b2Body **)dub_checksdata_n(L, 3, "b2.Body"));
      return 0;
    }
    case 6: {
      if (DUB_ASSERT_KEY(key, "collideConnected")) break;
      self->collideConnected = luaL_checkboolean(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2JointDef__get_(lua_State *L) {

  b2JointDef *self = *((b2JointDef **)dub_checksdata_n(L, 1, "b2.JointDef", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub_hash(key, 7);
  switch(key_h) {
    case 3: {
      if (DUB_ASSERT_KEY(key, "type")) break;
      lua_pushnumber(L, self->type);
      return 1;
    }
    case 2: {
      if (DUB_ASSERT_KEY(key, "userData")) break;
      void *retval__ = self->userData;
      if (!retval__) return 0;
      dub_pushudata(L, retval__, "void", false);
      return 1;
    }
    case 4: {
      if (DUB_ASSERT_KEY(key, "bodyA")) break;
      b2Body *retval__ = self->bodyA;
      if (!retval__) return 0;
      dub_pushudata(L, retval__, "b2.Body", false);
      return 1;
    }
    case 5: {
      if (DUB_ASSERT_KEY(key, "bodyB")) break;
      b2Body *retval__ = self->bodyB;
      if (!retval__) return 0;
      dub_pushudata(L, retval__, "b2.Body", false);
      return 1;
    }
    case 6: {
      if (DUB_ASSERT_KEY(key, "collideConnected")) break;
      lua_pushboolean(L, self->collideConnected);
      return 1;
    }
  }
  return 0;
}

/** b2JointDef::b2JointDef()
 * vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:78
 */
static int b2JointDef_b2JointDef(lua_State *L) {
  try {
    b2JointDef *retval__ = new b2JointDef();
    dub_pushudata(L, retval__, "b2.JointDef", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "b2JointDef: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "b2JointDef: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int b2JointDef___tostring(lua_State *L) {
  b2JointDef *self = *((b2JointDef **)dub_checksdata_n(L, 1, "b2.JointDef"));
  lua_pushfstring(L, "b2.JointDef: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2JointDef_member_methods[] = {
  { "__gc"         , b2JointDef__b2JointDef },
  { "__newindex"   , b2JointDef__set_     },
  { "__index"      , b2JointDef__get_     },
  { "new"          , b2JointDef_b2JointDef },
  { "__tostring"   , b2JointDef___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_b2_JointDef(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.JointDef");
  // <mt>

  // register member methods
  luaL_register(L, NULL, b2JointDef_member_methods);
  // save meta-table in b2
  dub_register(L, "b2", "JointDef", "JointDef");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
