/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2ManifoldPoint
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "Box2D/Collision/b2Collision.h"


/** Set attributes (key, value)
 * 
 */
static int b2ManifoldPoint__set_(lua_State *L) {

  b2ManifoldPoint *self = *((b2ManifoldPoint **)dub_checksdata_n(L, 1, "b2.ManifoldPoint"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub_hash(key, 4);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "localPoint")) break;
      self->localPoint = **((b2Vec2 **)dub_checksdata_n(L, 3, "b2.Vec2"));
      return 0;
    }
    case 2: {
      if (DUB_ASSERT_KEY(key, "normalImpulse")) break;
      self->normalImpulse = luaL_checknumber(L, 3);
      return 0;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "tangentImpulse")) break;
      self->tangentImpulse = luaL_checknumber(L, 3);
      return 0;
    }
    case 3: {
      if (DUB_ASSERT_KEY(key, "id")) break;
      self->id = **((b2ContactID **)dub_checksdata_n(L, 3, "b2.ContactID"));
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2ManifoldPoint__get_(lua_State *L) {

  b2ManifoldPoint *self = *((b2ManifoldPoint **)dub_checksdata_n(L, 1, "b2.ManifoldPoint", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub_hash(key, 4);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "localPoint")) break;
      dub_pushudata(L, &self->localPoint, "b2.Vec2", false);
      return 1;
    }
    case 2: {
      if (DUB_ASSERT_KEY(key, "normalImpulse")) break;
      lua_pushnumber(L, self->normalImpulse);
      return 1;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "tangentImpulse")) break;
      lua_pushnumber(L, self->tangentImpulse);
      return 1;
    }
    case 3: {
      if (DUB_ASSERT_KEY(key, "id")) break;
      dub_pushudata(L, &self->id, "b2.ContactID", false);
      return 1;
    }
  }
  return 0;
}

/** b2ManifoldPoint()
 * 
 */
static int b2ManifoldPoint_b2ManifoldPoint(lua_State *L) {
  try {
    b2ManifoldPoint *retval__ = new b2ManifoldPoint();
    dub_pushudata(L, retval__, "b2.ManifoldPoint", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "b2ManifoldPoint: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "b2ManifoldPoint: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int b2ManifoldPoint___tostring(lua_State *L) {
  b2ManifoldPoint *self = *((b2ManifoldPoint **)dub_checksdata_n(L, 1, "b2.ManifoldPoint"));
  lua_pushfstring(L, "b2.ManifoldPoint: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2ManifoldPoint_member_methods[] = {
  { "__newindex"   , b2ManifoldPoint__set_ },
  { "__index"      , b2ManifoldPoint__get_ },
  { "new"          , b2ManifoldPoint_b2ManifoldPoint },
  { "__tostring"   , b2ManifoldPoint___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_b2_ManifoldPoint(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.ManifoldPoint");
  // <mt>

  // register member methods
  luaL_register(L, NULL, b2ManifoldPoint_member_methods);
  // save meta-table in b2
  dub_register(L, "b2", "ManifoldPoint", "ManifoldPoint");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
