/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2Mat22
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "Box2D/Common/b2Math.h"


/** ~b2Mat22()
 * 
 */
static int b2Mat22__b2Mat22(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "b2.Mat22"));
    if (userdata->gc) {
      b2Mat22 *self = (b2Mat22 *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "~b2Mat22: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "~b2Mat22: Unknown exception");
  }
  return dub_error(L);
}

/** Set attributes (key, value)
 * 
 */
static int b2Mat22__set_(lua_State *L) {

  b2Mat22 *self = *((b2Mat22 **)dub_checksdata_n(L, 1, "b2.Mat22"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "ex")) break;
      self->ex = **((b2Vec2 **)dub_checksdata_n(L, 3, "b2.Vec2"));
      return 0;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "ey")) break;
      self->ey = **((b2Vec2 **)dub_checksdata_n(L, 3, "b2.Vec2"));
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2Mat22__get_(lua_State *L) {

  b2Mat22 *self = *((b2Mat22 **)dub_checksdata_n(L, 1, "b2.Mat22", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "ex")) break;
      dub_pushudata(L, &self->ex, "b2.Vec2", false);
      return 1;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "ey")) break;
      dub_pushudata(L, &self->ey, "b2.Vec2", false);
      return 1;
    }
  }
  return 0;
}

/** b2Mat22::b2Mat22()
 * vendor/Box2D/Box2D/Common/b2Math.h:214
 */
static int b2Mat22_b2Mat22(lua_State *L) {
  try {
    int top__ = lua_gettop(L);
    if (top__ >= 4) {
      float32 a11 = dub_checknumber(L, 1);
      float32 a12 = dub_checknumber(L, 2);
      float32 a21 = dub_checknumber(L, 3);
      float32 a22 = dub_checknumber(L, 4);
      b2Mat22 *retval__ = new b2Mat22(a11, a12, a21, a22);
      dub_pushudata(L, retval__, "b2.Mat22", true);
      return 1;
    } else if (top__ >= 2) {
      b2Vec2 *c1 = *((b2Vec2 **)dub_checksdata(L, 1, "b2.Vec2"));
      b2Vec2 *c2 = *((b2Vec2 **)dub_checksdata(L, 2, "b2.Vec2"));
      b2Mat22 *retval__ = new b2Mat22(*c1, *c2);
      dub_pushudata(L, retval__, "b2.Mat22", true);
      return 1;
    } else {
      b2Mat22 *retval__ = new b2Mat22();
      dub_pushudata(L, retval__, "b2.Mat22", true);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "b2Mat22: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "b2Mat22: Unknown exception");
  }
  return dub_error(L);
}

/** void b2Mat22::Set(const b2Vec2 &c1, const b2Vec2 &c2)
 * vendor/Box2D/Box2D/Common/b2Math.h:232
 */
static int b2Mat22_Set(lua_State *L) {
  try {
    b2Mat22 *self = *((b2Mat22 **)dub_checksdata(L, 1, "b2.Mat22"));
    b2Vec2 *c1 = *((b2Vec2 **)dub_checksdata(L, 2, "b2.Vec2"));
    b2Vec2 *c2 = *((b2Vec2 **)dub_checksdata(L, 3, "b2.Vec2"));
    self->Set(*c1, *c2);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "Set: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Set: Unknown exception");
  }
  return dub_error(L);
}

/** void b2Mat22::SetIdentity()
 * vendor/Box2D/Box2D/Common/b2Math.h:239
 */
static int b2Mat22_SetIdentity(lua_State *L) {
  try {
    b2Mat22 *self = *((b2Mat22 **)dub_checksdata(L, 1, "b2.Mat22"));
    self->SetIdentity();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "SetIdentity: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SetIdentity: Unknown exception");
  }
  return dub_error(L);
}

/** void b2Mat22::SetZero()
 * vendor/Box2D/Box2D/Common/b2Math.h:246
 */
static int b2Mat22_SetZero(lua_State *L) {
  try {
    b2Mat22 *self = *((b2Mat22 **)dub_checksdata(L, 1, "b2.Mat22"));
    self->SetZero();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "SetZero: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SetZero: Unknown exception");
  }
  return dub_error(L);
}

/** b2Mat22 b2Mat22::GetInverse() const
 * vendor/Box2D/Box2D/Common/b2Math.h:252
 */
static int b2Mat22_GetInverse(lua_State *L) {
  try {
    b2Mat22 *self = *((b2Mat22 **)dub_checksdata(L, 1, "b2.Mat22"));
    dub_pushudata(L, new b2Mat22(self->GetInverse()), "b2.Mat22", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetInverse: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetInverse: Unknown exception");
  }
  return dub_error(L);
}

/** b2Vec2 b2Mat22::Solve(const b2Vec2 &b) const
 * vendor/Box2D/Box2D/Common/b2Math.h:268
 */
static int b2Mat22_Solve(lua_State *L) {
  try {
    b2Mat22 *self = *((b2Mat22 **)dub_checksdata(L, 1, "b2.Mat22"));
    b2Vec2 *b = *((b2Vec2 **)dub_checksdata(L, 2, "b2.Vec2"));
    dub_pushudata(L, new b2Vec2(self->Solve(*b)), "b2.Vec2", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "Solve: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Solve: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int b2Mat22___tostring(lua_State *L) {
  b2Mat22 *self = *((b2Mat22 **)dub_checksdata_n(L, 1, "b2.Mat22"));
  lua_pushfstring(L, "b2.Mat22: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2Mat22_member_methods[] = {
  { "__gc"         , b2Mat22__b2Mat22     },
  { "__newindex"   , b2Mat22__set_        },
  { "__index"      , b2Mat22__get_        },
  { "new"          , b2Mat22_b2Mat22      },
  { "Set"          , b2Mat22_Set          },
  { "SetIdentity"  , b2Mat22_SetIdentity  },
  { "SetZero"      , b2Mat22_SetZero      },
  { "GetInverse"   , b2Mat22_GetInverse   },
  { "Solve"        , b2Mat22_Solve        },
  { "__tostring"   , b2Mat22___tostring   },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_b2_Mat22(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.Mat22");
  // <mt>

  // register member methods
  luaL_register(L, NULL, b2Mat22_member_methods);
  // save meta-table in b2
  dub_register(L, "b2", "Mat22", "Mat22");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
