/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2PrismaticJointDef
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "Box2D/Dynamics/Joints/b2PrismaticJoint.h"


/** ~b2PrismaticJointDef()
 * 
 */
static int b2PrismaticJointDef__b2PrismaticJointDef(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "b2.PrismaticJointDef"));
    if (userdata->gc) {
      b2PrismaticJointDef *self = (b2PrismaticJointDef *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "~b2PrismaticJointDef: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "~b2PrismaticJointDef: Unknown exception");
  }
  return dub_error(L);
}

/** Set attributes (key, value)
 * 
 */
static int b2PrismaticJointDef__set_(lua_State *L) {

  b2PrismaticJointDef *self = *((b2PrismaticJointDef **)dub_checksdata_n(L, 1, "b2.PrismaticJointDef"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub_hash(key, 43);
  switch(key_h) {
    case 14: {
      if (DUB_ASSERT_KEY(key, "localAnchorA")) break;
      self->localAnchorA = **((b2Vec2 **)dub_checksdata_n(L, 3, "b2.Vec2"));
      return 0;
    }
    case 15: {
      if (DUB_ASSERT_KEY(key, "localAnchorB")) break;
      self->localAnchorB = **((b2Vec2 **)dub_checksdata_n(L, 3, "b2.Vec2"));
      return 0;
    }
    case 20: {
      if (DUB_ASSERT_KEY(key, "localAxisA")) break;
      self->localAxisA = **((b2Vec2 **)dub_checksdata_n(L, 3, "b2.Vec2"));
      return 0;
    }
    case 38: {
      if (DUB_ASSERT_KEY(key, "referenceAngle")) break;
      self->referenceAngle = luaL_checknumber(L, 3);
      return 0;
    }
    case 39: {
      if (DUB_ASSERT_KEY(key, "enableLimit")) break;
      self->enableLimit = luaL_checkboolean(L, 3);
      return 0;
    }
    case 32: {
      if (DUB_ASSERT_KEY(key, "lowerTranslation")) break;
      self->lowerTranslation = luaL_checknumber(L, 3);
      return 0;
    }
    case 40: {
      if (DUB_ASSERT_KEY(key, "upperTranslation")) break;
      self->upperTranslation = luaL_checknumber(L, 3);
      return 0;
    }
    case 33: {
      if (DUB_ASSERT_KEY(key, "enableMotor")) break;
      self->enableMotor = luaL_checkboolean(L, 3);
      return 0;
    }
    case 30: {
      if (DUB_ASSERT_KEY(key, "maxMotorForce")) break;
      self->maxMotorForce = luaL_checknumber(L, 3);
      return 0;
    }
    case 3: {
      if (DUB_ASSERT_KEY(key, "motorSpeed")) break;
      self->motorSpeed = luaL_checknumber(L, 3);
      return 0;
    }
    case 4: {
      if (DUB_ASSERT_KEY(key, "type")) break;
      self->type = (b2JointType)luaL_checkint(L, 3);
      return 0;
    }
    case 22: {
      if (DUB_ASSERT_KEY(key, "userData")) break;
      dub_protect(L, 1, 3, "userData");
      self->userData = *((void **)dub_checksdata_n(L, 3, "void"));
      return 0;
    }
    case 10: {
      if (DUB_ASSERT_KEY(key, "bodyA")) break;
      dub_protect(L, 1, 3, "bodyA");
      self->bodyA = *((b2Body **)dub_checksdata_n(L, 3, "b2.Body"));
      return 0;
    }
    case 11: {
      if (DUB_ASSERT_KEY(key, "bodyB")) break;
      dub_protect(L, 1, 3, "bodyB");
      self->bodyB = *((b2Body **)dub_checksdata_n(L, 3, "b2.Body"));
      return 0;
    }
    case 35: {
      if (DUB_ASSERT_KEY(key, "collideConnected")) break;
      self->collideConnected = luaL_checkboolean(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2PrismaticJointDef__get_(lua_State *L) {

  b2PrismaticJointDef *self = *((b2PrismaticJointDef **)dub_checksdata_n(L, 1, "b2.PrismaticJointDef", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub_hash(key, 43);
  switch(key_h) {
    case 14: {
      if (DUB_ASSERT_KEY(key, "localAnchorA")) break;
      dub_pushudata(L, &self->localAnchorA, "b2.Vec2", false);
      return 1;
    }
    case 15: {
      if (DUB_ASSERT_KEY(key, "localAnchorB")) break;
      dub_pushudata(L, &self->localAnchorB, "b2.Vec2", false);
      return 1;
    }
    case 20: {
      if (DUB_ASSERT_KEY(key, "localAxisA")) break;
      dub_pushudata(L, &self->localAxisA, "b2.Vec2", false);
      return 1;
    }
    case 38: {
      if (DUB_ASSERT_KEY(key, "referenceAngle")) break;
      lua_pushnumber(L, self->referenceAngle);
      return 1;
    }
    case 39: {
      if (DUB_ASSERT_KEY(key, "enableLimit")) break;
      lua_pushboolean(L, self->enableLimit);
      return 1;
    }
    case 32: {
      if (DUB_ASSERT_KEY(key, "lowerTranslation")) break;
      lua_pushnumber(L, self->lowerTranslation);
      return 1;
    }
    case 40: {
      if (DUB_ASSERT_KEY(key, "upperTranslation")) break;
      lua_pushnumber(L, self->upperTranslation);
      return 1;
    }
    case 33: {
      if (DUB_ASSERT_KEY(key, "enableMotor")) break;
      lua_pushboolean(L, self->enableMotor);
      return 1;
    }
    case 30: {
      if (DUB_ASSERT_KEY(key, "maxMotorForce")) break;
      lua_pushnumber(L, self->maxMotorForce);
      return 1;
    }
    case 3: {
      if (DUB_ASSERT_KEY(key, "motorSpeed")) break;
      lua_pushnumber(L, self->motorSpeed);
      return 1;
    }
    case 4: {
      if (DUB_ASSERT_KEY(key, "type")) break;
      lua_pushnumber(L, self->type);
      return 1;
    }
    case 22: {
      if (DUB_ASSERT_KEY(key, "userData")) break;
      void *retval__ = self->userData;
      if (!retval__) return 0;
      dub_pushudata(L, retval__, "void", false);
      return 1;
    }
    case 10: {
      if (DUB_ASSERT_KEY(key, "bodyA")) break;
      b2Body *retval__ = self->bodyA;
      if (!retval__) return 0;
      dub_pushudata(L, retval__, "b2.Body", false);
      return 1;
    }
    case 11: {
      if (DUB_ASSERT_KEY(key, "bodyB")) break;
      b2Body *retval__ = self->bodyB;
      if (!retval__) return 0;
      dub_pushudata(L, retval__, "b2.Body", false);
      return 1;
    }
    case 35: {
      if (DUB_ASSERT_KEY(key, "collideConnected")) break;
      lua_pushboolean(L, self->collideConnected);
      return 1;
    }
  }
  return 0;
}

/** Cast (class_name)
 * 
 */
static int b2PrismaticJointDef__cast_(lua_State *L) {

  b2PrismaticJointDef *self = *((b2PrismaticJointDef **)dub_checksdata_n(L, 1, "b2.PrismaticJointDef"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "b2.JointDef")) break;
      *retval__ = static_cast<b2JointDef *>(self);
      return 1;
    }
  }
  return 0;
}

/** b2PrismaticJointDef::b2PrismaticJointDef()
 * vendor/Box2D/Box2D/Dynamics/Joints/b2PrismaticJoint.h:33
 */
static int b2PrismaticJointDef_b2PrismaticJointDef(lua_State *L) {
  try {
    b2PrismaticJointDef *retval__ = new b2PrismaticJointDef();
    dub_pushudata(L, retval__, "b2.PrismaticJointDef", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "b2PrismaticJointDef: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "b2PrismaticJointDef: Unknown exception");
  }
  return dub_error(L);
}

/** void b2PrismaticJointDef::Initialize(b2Body *bodyA, b2Body *bodyB, const b2Vec2 &anchor, const b2Vec2 &axis)
 * vendor/Box2D/Box2D/Dynamics/Joints/b2PrismaticJoint.h:49
 */
static int b2PrismaticJointDef_Initialize(lua_State *L) {
  try {
    b2PrismaticJointDef *self = *((b2PrismaticJointDef **)dub_checksdata(L, 1, "b2.PrismaticJointDef"));
    b2Body *bodyA = *((b2Body **)dub_checksdata(L, 2, "b2.Body"));
    b2Body *bodyB = *((b2Body **)dub_checksdata(L, 3, "b2.Body"));
    b2Vec2 *anchor = *((b2Vec2 **)dub_checksdata(L, 4, "b2.Vec2"));
    b2Vec2 *axis = *((b2Vec2 **)dub_checksdata(L, 5, "b2.Vec2"));
    self->Initialize(bodyA, bodyB, *anchor, *axis);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "Initialize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Initialize: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int b2PrismaticJointDef___tostring(lua_State *L) {
  b2PrismaticJointDef *self = *((b2PrismaticJointDef **)dub_checksdata_n(L, 1, "b2.PrismaticJointDef"));
  lua_pushfstring(L, "b2.PrismaticJointDef: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2PrismaticJointDef_member_methods[] = {
  { "__gc"         , b2PrismaticJointDef__b2PrismaticJointDef },
  { "__newindex"   , b2PrismaticJointDef__set_ },
  { "__index"      , b2PrismaticJointDef__get_ },
  { "_cast_"       , b2PrismaticJointDef__cast_ },
  { "new"          , b2PrismaticJointDef_b2PrismaticJointDef },
  { "Initialize"   , b2PrismaticJointDef_Initialize },
  { "__tostring"   , b2PrismaticJointDef___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_b2_PrismaticJointDef(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.PrismaticJointDef");
  // <mt>

  // register member methods
  luaL_register(L, NULL, b2PrismaticJointDef_member_methods);
  // save meta-table in b2
  dub_register(L, "b2", "PrismaticJointDef", "PrismaticJointDef");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
