/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2Shape
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "Box2D/Collision/Shapes/b2Shape.h"


/** Set attributes (key, value)
 * 
 */
static int b2Shape__set_(lua_State *L) {

  b2Shape *self = *((b2Shape **)dub_checksdata_n(L, 1, "b2.Shape"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub_hash(key, 5);
  switch(key_h) {
    case 2: {
      if (DUB_ASSERT_KEY(key, "m_type")) break;
      self->m_type = (b2Shape::Type)luaL_checkint(L, 3);
      return 0;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "m_radius")) break;
      self->m_radius = luaL_checknumber(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2Shape__get_(lua_State *L) {

  b2Shape *self = *((b2Shape **)dub_checksdata_n(L, 1, "b2.Shape", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub_hash(key, 5);
  switch(key_h) {
    case 2: {
      if (DUB_ASSERT_KEY(key, "m_type")) break;
      lua_pushnumber(L, self->m_type);
      return 1;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "m_radius")) break;
      lua_pushnumber(L, self->m_radius);
      return 1;
    }
  }
  return 0;
}

/** virtual b2Shape::~b2Shape()
 * vendor/Box2D/Box2D/Collision/Shapes/b2Shape.h:55
 */
static int b2Shape__b2Shape(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "b2.Shape"));
    if (userdata->gc) {
      b2Shape *self = (b2Shape *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "~b2Shape: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "~b2Shape: Unknown exception");
  }
  return dub_error(L);
}

/** virtual b2Shape* b2Shape::Clone(b2BlockAllocator *allocator) const =0
 * vendor/Box2D/Box2D/Collision/Shapes/b2Shape.h:58
 */
static int b2Shape_Clone(lua_State *L) {
  try {
    b2Shape *self = *((b2Shape **)dub_checksdata(L, 1, "b2.Shape"));
    b2BlockAllocator *allocator = *((b2BlockAllocator **)dub_checksdata(L, 2, "b2.BlockAllocator"));
    b2Shape *retval__ = self->Clone(allocator);
    if (!retval__) return 0;
    dub_pushudata(L, retval__, "b2.Shape", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "Clone: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Clone: Unknown exception");
  }
  return dub_error(L);
}

/** b2Shape::Type b2Shape::GetType() const
 * vendor/Box2D/Box2D/Collision/Shapes/b2Shape.h:62
 */
static int b2Shape_GetType(lua_State *L) {
  try {
    b2Shape *self = *((b2Shape **)dub_checksdata(L, 1, "b2.Shape"));
    lua_pushnumber(L, self->GetType());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetType: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetType: Unknown exception");
  }
  return dub_error(L);
}

/** virtual int32 b2Shape::GetChildCount() const =0
 * vendor/Box2D/Box2D/Collision/Shapes/b2Shape.h:65
 */
static int b2Shape_GetChildCount(lua_State *L) {
  try {
    b2Shape *self = *((b2Shape **)dub_checksdata(L, 1, "b2.Shape"));
    lua_pushnumber(L, self->GetChildCount());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetChildCount: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetChildCount: Unknown exception");
  }
  return dub_error(L);
}

/** virtual bool b2Shape::TestPoint(const b2Transform &xf, const b2Vec2 &p) const =0
 * vendor/Box2D/Box2D/Collision/Shapes/b2Shape.h:70
 */
static int b2Shape_TestPoint(lua_State *L) {
  try {
    b2Shape *self = *((b2Shape **)dub_checksdata(L, 1, "b2.Shape"));
    b2Transform *xf = *((b2Transform **)dub_checksdata(L, 2, "b2.Transform"));
    b2Vec2 *p = *((b2Vec2 **)dub_checksdata(L, 3, "b2.Vec2"));
    lua_pushboolean(L, self->TestPoint(*xf, *p));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "TestPoint: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "TestPoint: Unknown exception");
  }
  return dub_error(L);
}

/** virtual bool b2Shape::RayCast(b2RayCastOutput *output, const b2RayCastInput &input, const b2Transform &transform, int32 childIndex) const =0
 * vendor/Box2D/Box2D/Collision/Shapes/b2Shape.h:78
 */
static int b2Shape_RayCast(lua_State *L) {
  try {
    b2Shape *self = *((b2Shape **)dub_checksdata(L, 1, "b2.Shape"));
    b2RayCastOutput *output = *((b2RayCastOutput **)dub_checksdata(L, 2, "b2.RayCastOutput"));
    b2RayCastInput *input = *((b2RayCastInput **)dub_checksdata(L, 3, "b2.RayCastInput"));
    b2Transform *transform = *((b2Transform **)dub_checksdata(L, 4, "b2.Transform"));
    int32 childIndex = dub_checkint(L, 5);
    lua_pushboolean(L, self->RayCast(output, *input, *transform, childIndex));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "RayCast: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "RayCast: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void b2Shape::ComputeAABB(b2AABB *aabb, const b2Transform &xf, int32 childIndex) const =0
 * vendor/Box2D/Box2D/Collision/Shapes/b2Shape.h:84
 */
static int b2Shape_ComputeAABB(lua_State *L) {
  try {
    b2Shape *self = *((b2Shape **)dub_checksdata(L, 1, "b2.Shape"));
    b2AABB *aabb = *((b2AABB **)dub_checksdata(L, 2, "b2.AABB"));
    b2Transform *xf = *((b2Transform **)dub_checksdata(L, 3, "b2.Transform"));
    int32 childIndex = dub_checkint(L, 4);
    self->ComputeAABB(aabb, *xf, childIndex);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "ComputeAABB: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "ComputeAABB: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void b2Shape::ComputeMass(b2MassData *massData, float32 density) const =0
 * vendor/Box2D/Box2D/Collision/Shapes/b2Shape.h:90
 */
static int b2Shape_ComputeMass(lua_State *L) {
  try {
    b2Shape *self = *((b2Shape **)dub_checksdata(L, 1, "b2.Shape"));
    b2MassData *massData = *((b2MassData **)dub_checksdata(L, 2, "b2.MassData"));
    float32 density = dub_checknumber(L, 3);
    self->ComputeMass(massData, density);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "ComputeMass: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "ComputeMass: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int b2Shape___tostring(lua_State *L) {
  b2Shape *self = *((b2Shape **)dub_checksdata_n(L, 1, "b2.Shape"));
  lua_pushfstring(L, "b2.Shape: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2Shape_member_methods[] = {
  { "__newindex"   , b2Shape__set_        },
  { "__index"      , b2Shape__get_        },
  { "__gc"         , b2Shape__b2Shape     },
  { "Clone"        , b2Shape_Clone        },
  { "GetType"      , b2Shape_GetType      },
  { "GetChildCount", b2Shape_GetChildCount },
  { "TestPoint"    , b2Shape_TestPoint    },
  { "RayCast"      , b2Shape_RayCast      },
  { "ComputeAABB"  , b2Shape_ComputeAABB  },
  { "ComputeMass"  , b2Shape_ComputeMass  },
  { "__tostring"   , b2Shape___tostring   },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};

// --=============================================== CONSTANTS
static const struct dub_const_Reg b2Shape_const[] = {
  { "e_circle"     , b2Shape::e_circle    },
  { "e_edge"       , b2Shape::e_edge      },
  { "e_polygon"    , b2Shape::e_polygon   },
  { "e_chain"      , b2Shape::e_chain     },
  { "e_typeCount"  , b2Shape::e_typeCount },
  { NULL, 0},
};

extern "C" int luaopen_b2_Shape(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.Shape");
  // <mt>
  // register class constants
  dub_register_const(L, b2Shape_const);

  // register member methods
  luaL_register(L, NULL, b2Shape_member_methods);
  // save meta-table in b2
  dub_register(L, "b2", "Shape", "Shape");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
