/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2TOIOutput
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "Box2D/Collision/b2TimeOfImpact.h"


/** Set attributes (key, value)
 * 
 */
static int b2TOIOutput__set_(lua_State *L) {

  b2TOIOutput *self = *((b2TOIOutput **)dub_checksdata_n(L, 1, "b2.TOIOutput"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "state")) break;
      self->state = (b2TOIOutput::State)luaL_checkint(L, 3);
      return 0;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "t")) break;
      self->t = luaL_checknumber(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2TOIOutput__get_(lua_State *L) {

  b2TOIOutput *self = *((b2TOIOutput **)dub_checksdata_n(L, 1, "b2.TOIOutput", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "state")) break;
      lua_pushnumber(L, self->state);
      return 1;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "t")) break;
      lua_pushnumber(L, self->t);
      return 1;
    }
  }
  return 0;
}

/** b2TOIOutput()
 * 
 */
static int b2TOIOutput_b2TOIOutput(lua_State *L) {
  try {
    b2TOIOutput *retval__ = new b2TOIOutput();
    dub_pushudata(L, retval__, "b2.TOIOutput", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "b2TOIOutput: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "b2TOIOutput: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int b2TOIOutput___tostring(lua_State *L) {
  b2TOIOutput *self = *((b2TOIOutput **)dub_checksdata_n(L, 1, "b2.TOIOutput"));
  lua_pushfstring(L, "b2.TOIOutput: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2TOIOutput_member_methods[] = {
  { "__newindex"   , b2TOIOutput__set_    },
  { "__index"      , b2TOIOutput__get_    },
  { "new"          , b2TOIOutput_b2TOIOutput },
  { "__tostring"   , b2TOIOutput___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};

// --=============================================== CONSTANTS
static const struct dub_const_Reg b2TOIOutput_const[] = {
  { "e_unknown"    , b2TOIOutput::e_unknown },
  { "e_failed"     , b2TOIOutput::e_failed },
  { "e_overlapped" , b2TOIOutput::e_overlapped },
  { "e_touching"   , b2TOIOutput::e_touching },
  { "e_separated"  , b2TOIOutput::e_separated },
  { NULL, 0},
};

extern "C" int luaopen_b2_TOIOutput(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.TOIOutput");
  // <mt>
  // register class constants
  dub_register_const(L, b2TOIOutput_const);

  // register member methods
  luaL_register(L, NULL, b2TOIOutput_member_methods);
  // save meta-table in b2
  dub_register(L, "b2", "TOIOutput", "TOIOutput");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
