/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2Transform
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "Box2D/Common/b2Math.h"


/** ~b2Transform()
 * 
 */
static int b2Transform__b2Transform(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "b2.Transform"));
    if (userdata->gc) {
      b2Transform *self = (b2Transform *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "~b2Transform: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "~b2Transform: Unknown exception");
  }
  return dub_error(L);
}

/** Set attributes (key, value)
 * 
 */
static int b2Transform__set_(lua_State *L) {

  b2Transform *self = *((b2Transform **)dub_checksdata_n(L, 1, "b2.Transform"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "p")) break;
      self->p = **((b2Vec2 **)dub_checksdata_n(L, 3, "b2.Vec2"));
      return 0;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "q")) break;
      self->q = **((b2Rot **)dub_checksdata_n(L, 3, "b2.Rot"));
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2Transform__get_(lua_State *L) {

  b2Transform *self = *((b2Transform **)dub_checksdata_n(L, 1, "b2.Transform", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "p")) break;
      dub_pushudata(L, &self->p, "b2.Vec2", false);
      return 1;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "q")) break;
      dub_pushudata(L, &self->q, "b2.Rot", false);
      return 1;
    }
  }
  return 0;
}

/** b2Transform::b2Transform()
 * vendor/Box2D/Box2D/Common/b2Math.h:381
 */
static int b2Transform_b2Transform(lua_State *L) {
  try {
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      b2Vec2 *position = *((b2Vec2 **)dub_checksdata(L, 1, "b2.Vec2"));
      b2Rot *rotation = *((b2Rot **)dub_checksdata(L, 2, "b2.Rot"));
      b2Transform *retval__ = new b2Transform(*position, *rotation);
      dub_pushudata(L, retval__, "b2.Transform", true);
      return 1;
    } else {
      b2Transform *retval__ = new b2Transform();
      dub_pushudata(L, retval__, "b2.Transform", true);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "b2Transform: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "b2Transform: Unknown exception");
  }
  return dub_error(L);
}

/** void b2Transform::SetIdentity()
 * vendor/Box2D/Box2D/Common/b2Math.h:388
 */
static int b2Transform_SetIdentity(lua_State *L) {
  try {
    b2Transform *self = *((b2Transform **)dub_checksdata(L, 1, "b2.Transform"));
    self->SetIdentity();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "SetIdentity: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SetIdentity: Unknown exception");
  }
  return dub_error(L);
}

/** void b2Transform::Set(const b2Vec2 &position, float32 angle)
 * vendor/Box2D/Box2D/Common/b2Math.h:395
 */
static int b2Transform_Set(lua_State *L) {
  try {
    b2Transform *self = *((b2Transform **)dub_checksdata(L, 1, "b2.Transform"));
    b2Vec2 *position = *((b2Vec2 **)dub_checksdata(L, 2, "b2.Vec2"));
    float32 angle = dub_checknumber(L, 3);
    self->Set(*position, angle);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "Set: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Set: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int b2Transform___tostring(lua_State *L) {
  b2Transform *self = *((b2Transform **)dub_checksdata_n(L, 1, "b2.Transform"));
  lua_pushfstring(L, "b2.Transform: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2Transform_member_methods[] = {
  { "__gc"         , b2Transform__b2Transform },
  { "__newindex"   , b2Transform__set_    },
  { "__index"      , b2Transform__get_    },
  { "new"          , b2Transform_b2Transform },
  { "SetIdentity"  , b2Transform_SetIdentity },
  { "Set"          , b2Transform_Set      },
  { "__tostring"   , b2Transform___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_b2_Transform(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.Transform");
  // <mt>

  // register member methods
  luaL_register(L, NULL, b2Transform_member_methods);
  // save meta-table in b2
  dub_register(L, "b2", "Transform", "Transform");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
