/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2Version
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "Box2D/Common/b2Settings.h"


/** Set attributes (key, value)
 * 
 */
static int b2Version__set_(lua_State *L) {

  b2Version *self = *((b2Version **)dub_checksdata_n(L, 1, "b2.Version"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub_hash(key, 3);
  switch(key_h) {
    case 2: {
      if (DUB_ASSERT_KEY(key, "major")) break;
      self->major = luaL_checkint(L, 3);
      return 0;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "minor")) break;
      self->minor = luaL_checkint(L, 3);
      return 0;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "revision")) break;
      self->revision = luaL_checkint(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2Version__get_(lua_State *L) {

  b2Version *self = *((b2Version **)dub_checksdata_n(L, 1, "b2.Version", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub_hash(key, 3);
  switch(key_h) {
    case 2: {
      if (DUB_ASSERT_KEY(key, "major")) break;
      lua_pushnumber(L, self->major);
      return 1;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "minor")) break;
      lua_pushnumber(L, self->minor);
      return 1;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "revision")) break;
      lua_pushnumber(L, self->revision);
      return 1;
    }
  }
  return 0;
}

/** b2Version()
 * 
 */
static int b2Version_b2Version(lua_State *L) {
  try {
    b2Version *retval__ = new b2Version();
    dub_pushudata(L, retval__, "b2.Version", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "b2Version: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "b2Version: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int b2Version___tostring(lua_State *L) {
  b2Version *self = *((b2Version **)dub_checksdata_n(L, 1, "b2.Version"));
  lua_pushfstring(L, "b2.Version: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2Version_member_methods[] = {
  { "__newindex"   , b2Version__set_      },
  { "__index"      , b2Version__get_      },
  { "new"          , b2Version_b2Version  },
  { "__tostring"   , b2Version___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_b2_Version(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.Version");
  // <mt>

  // register member methods
  luaL_register(L, NULL, b2Version_member_methods);
  // save meta-table in b2
  dub_register(L, "b2", "Version", "Version");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
