/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2WeldJoint
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "Box2D/Dynamics/Joints/b2WeldJoint.h"


/** ~b2WeldJoint()
 * 
 */
static int b2WeldJoint__b2WeldJoint(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "b2.WeldJoint"));
    if (userdata->gc) {
      b2WeldJoint *self = (b2WeldJoint *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "~b2WeldJoint: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "~b2WeldJoint: Unknown exception");
  }
  return dub_error(L);
}

/** Cast (class_name)
 * 
 */
static int b2WeldJoint__cast_(lua_State *L) {

  b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata_n(L, 1, "b2.WeldJoint"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "b2.Joint")) break;
      *retval__ = static_cast<b2Joint *>(self);
      return 1;
    }
  }
  return 0;
}

/** b2Vec2 b2WeldJoint::GetAnchorA() const
 * vendor/Box2D/Box2D/Dynamics/Joints/b2WeldJoint.h:65
 */
static int b2WeldJoint_GetAnchorA(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    dub_pushudata(L, new b2Vec2(self->GetAnchorA()), "b2.Vec2", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetAnchorA: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetAnchorA: Unknown exception");
  }
  return dub_error(L);
}

/** b2Vec2 b2WeldJoint::GetAnchorB() const
 * vendor/Box2D/Box2D/Dynamics/Joints/b2WeldJoint.h:66
 */
static int b2WeldJoint_GetAnchorB(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    dub_pushudata(L, new b2Vec2(self->GetAnchorB()), "b2.Vec2", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetAnchorB: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetAnchorB: Unknown exception");
  }
  return dub_error(L);
}

/** b2Vec2 b2WeldJoint::GetReactionForce(float32 inv_dt) const
 * vendor/Box2D/Box2D/Dynamics/Joints/b2WeldJoint.h:68
 */
static int b2WeldJoint_GetReactionForce(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    float32 inv_dt = dub_checknumber(L, 2);
    dub_pushudata(L, new b2Vec2(self->GetReactionForce(inv_dt)), "b2.Vec2", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetReactionForce: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetReactionForce: Unknown exception");
  }
  return dub_error(L);
}

/** float32 b2WeldJoint::GetReactionTorque(float32 inv_dt) const
 * vendor/Box2D/Box2D/Dynamics/Joints/b2WeldJoint.h:69
 */
static int b2WeldJoint_GetReactionTorque(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    float32 inv_dt = dub_checknumber(L, 2);
    lua_pushnumber(L, self->GetReactionTorque(inv_dt));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetReactionTorque: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetReactionTorque: Unknown exception");
  }
  return dub_error(L);
}

/** const b2Vec2& b2WeldJoint::GetLocalAnchorA() const
 * vendor/Box2D/Box2D/Dynamics/Joints/b2WeldJoint.h:72
 */
static int b2WeldJoint_GetLocalAnchorA(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    dub_pushudata(L, const_cast<b2Vec2*>(&self->GetLocalAnchorA()), "b2.Vec2", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetLocalAnchorA: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetLocalAnchorA: Unknown exception");
  }
  return dub_error(L);
}

/** const b2Vec2& b2WeldJoint::GetLocalAnchorB() const
 * vendor/Box2D/Box2D/Dynamics/Joints/b2WeldJoint.h:75
 */
static int b2WeldJoint_GetLocalAnchorB(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    dub_pushudata(L, const_cast<b2Vec2*>(&self->GetLocalAnchorB()), "b2.Vec2", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetLocalAnchorB: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetLocalAnchorB: Unknown exception");
  }
  return dub_error(L);
}

/** float32 b2WeldJoint::GetReferenceAngle() const
 * vendor/Box2D/Box2D/Dynamics/Joints/b2WeldJoint.h:78
 */
static int b2WeldJoint_GetReferenceAngle(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    lua_pushnumber(L, self->GetReferenceAngle());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetReferenceAngle: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetReferenceAngle: Unknown exception");
  }
  return dub_error(L);
}

/** void b2WeldJoint::SetFrequency(float32 hz)
 * vendor/Box2D/Box2D/Dynamics/Joints/b2WeldJoint.h:81
 */
static int b2WeldJoint_SetFrequency(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    float32 hz = dub_checknumber(L, 2);
    self->SetFrequency(hz);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "SetFrequency: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SetFrequency: Unknown exception");
  }
  return dub_error(L);
}

/** float32 b2WeldJoint::GetFrequency() const
 * vendor/Box2D/Box2D/Dynamics/Joints/b2WeldJoint.h:82
 */
static int b2WeldJoint_GetFrequency(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    lua_pushnumber(L, self->GetFrequency());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetFrequency: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetFrequency: Unknown exception");
  }
  return dub_error(L);
}

/** void b2WeldJoint::SetDampingRatio(float32 ratio)
 * vendor/Box2D/Box2D/Dynamics/Joints/b2WeldJoint.h:85
 */
static int b2WeldJoint_SetDampingRatio(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    float32 ratio = dub_checknumber(L, 2);
    self->SetDampingRatio(ratio);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "SetDampingRatio: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SetDampingRatio: Unknown exception");
  }
  return dub_error(L);
}

/** float32 b2WeldJoint::GetDampingRatio() const
 * vendor/Box2D/Box2D/Dynamics/Joints/b2WeldJoint.h:86
 */
static int b2WeldJoint_GetDampingRatio(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    lua_pushnumber(L, self->GetDampingRatio());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetDampingRatio: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetDampingRatio: Unknown exception");
  }
  return dub_error(L);
}

/** void b2WeldJoint::Dump()
 * vendor/Box2D/Box2D/Dynamics/Joints/b2WeldJoint.h:89
 */
static int b2WeldJoint_Dump(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    self->Dump();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "Dump: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Dump: Unknown exception");
  }
  return dub_error(L);
}

/** b2JointType b2Joint::GetType() const
 * vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:109
 */
static int b2WeldJoint_GetType(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    lua_pushnumber(L, self->GetType());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetType: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetType: Unknown exception");
  }
  return dub_error(L);
}

/** b2Body * b2Joint::GetBodyA()
 * vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:112
 */
static int b2WeldJoint_GetBodyA(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    b2Body *retval__ = self->GetBodyA();
    if (!retval__) return 0;
    dub_pushudata(L, retval__, "b2.Body", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetBodyA: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetBodyA: Unknown exception");
  }
  return dub_error(L);
}

/** b2Body * b2Joint::GetBodyB()
 * vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:115
 */
static int b2WeldJoint_GetBodyB(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    b2Body *retval__ = self->GetBodyB();
    if (!retval__) return 0;
    dub_pushudata(L, retval__, "b2.Body", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetBodyB: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetBodyB: Unknown exception");
  }
  return dub_error(L);
}

/** b2Joint * b2Joint::GetNext()
 * vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:130
 */
static int b2WeldJoint_GetNext(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    b2Joint *retval__ = self->GetNext();
    if (!retval__) return 0;
    dub_pushudata(L, retval__, "b2.Joint", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetNext: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetNext: Unknown exception");
  }
  return dub_error(L);
}

/** void * b2Joint::GetUserData() const
 * vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:134
 */
static int b2WeldJoint_GetUserData(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    self->GetUserData();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetUserData: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetUserData: Unknown exception");
  }
  return dub_error(L);
}

/** void b2Joint::SetUserData(void *data)
 * vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:137
 */
static int b2WeldJoint_SetUserData(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    void *data = *((void **)dub_checksdata(L, 2, "void"));
    self->SetUserData(data);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "SetUserData: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SetUserData: Unknown exception");
  }
  return dub_error(L);
}

/** bool b2Joint::IsActive() const
 * vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:140
 */
static int b2WeldJoint_IsActive(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    lua_pushboolean(L, self->IsActive());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "IsActive: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "IsActive: Unknown exception");
  }
  return dub_error(L);
}

/** bool b2Joint::GetCollideConnected() const
 * vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:145
 */
static int b2WeldJoint_GetCollideConnected(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    lua_pushboolean(L, self->GetCollideConnected());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetCollideConnected: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetCollideConnected: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void b2Joint::ShiftOrigin(const b2Vec2 &newOrigin)
 * vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:151
 */
static int b2WeldJoint_ShiftOrigin(lua_State *L) {
  try {
    b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata(L, 1, "b2.WeldJoint"));
    b2Vec2 *newOrigin = *((b2Vec2 **)dub_checksdata(L, 2, "b2.Vec2"));
    self->ShiftOrigin(*newOrigin);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "ShiftOrigin: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "ShiftOrigin: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int b2WeldJoint___tostring(lua_State *L) {
  b2WeldJoint *self = *((b2WeldJoint **)dub_checksdata_n(L, 1, "b2.WeldJoint"));
  lua_pushfstring(L, "b2.WeldJoint: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2WeldJoint_member_methods[] = {
  { "__gc"         , b2WeldJoint__b2WeldJoint },
  { "_cast_"       , b2WeldJoint__cast_   },
  { "GetAnchorA"   , b2WeldJoint_GetAnchorA },
  { "GetAnchorB"   , b2WeldJoint_GetAnchorB },
  { "GetReactionForce", b2WeldJoint_GetReactionForce },
  { "GetReactionTorque", b2WeldJoint_GetReactionTorque },
  { "GetLocalAnchorA", b2WeldJoint_GetLocalAnchorA },
  { "GetLocalAnchorB", b2WeldJoint_GetLocalAnchorB },
  { "GetReferenceAngle", b2WeldJoint_GetReferenceAngle },
  { "SetFrequency" , b2WeldJoint_SetFrequency },
  { "GetFrequency" , b2WeldJoint_GetFrequency },
  { "SetDampingRatio", b2WeldJoint_SetDampingRatio },
  { "GetDampingRatio", b2WeldJoint_GetDampingRatio },
  { "Dump"         , b2WeldJoint_Dump     },
  { "GetType"      , b2WeldJoint_GetType  },
  { "GetBodyA"     , b2WeldJoint_GetBodyA },
  { "GetBodyB"     , b2WeldJoint_GetBodyB },
  { "GetNext"      , b2WeldJoint_GetNext  },
  { "GetUserData"  , b2WeldJoint_GetUserData },
  { "SetUserData"  , b2WeldJoint_SetUserData },
  { "IsActive"     , b2WeldJoint_IsActive },
  { "GetCollideConnected", b2WeldJoint_GetCollideConnected },
  { "ShiftOrigin"  , b2WeldJoint_ShiftOrigin },
  { "__tostring"   , b2WeldJoint___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_b2_WeldJoint(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.WeldJoint");
  // <mt>

  // register member methods
  luaL_register(L, NULL, b2WeldJoint_member_methods);
  // save meta-table in b2
  dub_register(L, "b2", "WeldJoint", "WeldJoint");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
