/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2WorldManifold
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "Box2D/Collision/b2Collision.h"


/** Set attributes (key, value)
 * 
 */
static int b2WorldManifold__set_(lua_State *L) {

  b2WorldManifold *self = *((b2WorldManifold **)dub_checksdata_n(L, 1, "b2.WorldManifold"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "normal")) break;
      self->normal = **((b2Vec2 **)dub_checksdata_n(L, 3, "b2.Vec2"));
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2WorldManifold__get_(lua_State *L) {

  b2WorldManifold *self = *((b2WorldManifold **)dub_checksdata_n(L, 1, "b2.WorldManifold", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "normal")) break;
      dub_pushudata(L, &self->normal, "b2.Vec2", false);
      return 1;
    }
  }
  return 0;
}

/** b2WorldManifold()
 * 
 */
static int b2WorldManifold_b2WorldManifold(lua_State *L) {
  try {
    b2WorldManifold *retval__ = new b2WorldManifold();
    dub_pushudata(L, retval__, "b2.WorldManifold", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "b2WorldManifold: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "b2WorldManifold: Unknown exception");
  }
  return dub_error(L);
}

/** Read points(size_t i)
 * 
 */
static int b2WorldManifold_points(lua_State *L) {
  try {
    b2WorldManifold *self = *((b2WorldManifold **)dub_checksdata(L, 1, "b2.WorldManifold"));
    int top__ = lua_gettop(L);
    if (top__ >= 3) {
      size_t i = dub_checkint(L, 2);
      b2Vec2 *v = *((b2Vec2 **)dub_checksdata(L, 3, "b2.Vec2"));
      if (!i || i > b2_maxManifoldPoints) return 0;
      self->points[i-1] = *v;
      return 0;
    } else {
      size_t i = dub_checkint(L, 2);
      if (!i || i > b2_maxManifoldPoints) return 0;
      dub_pushudata(L, new b2Vec2(self->points[i-1]), "b2.Vec2", true);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "points: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "points: Unknown exception");
  }
  return dub_error(L);
}

/** void b2WorldManifold::Initialize(const b2Manifold *manifold, const b2Transform &xfA, float32 radiusA, const b2Transform &xfB, float32 radiusB)
 * vendor/Box2D/Box2D/Collision/b2Collision.h:118
 */
static int b2WorldManifold_Initialize(lua_State *L) {
  try {
    b2WorldManifold *self = *((b2WorldManifold **)dub_checksdata(L, 1, "b2.WorldManifold"));
    b2Manifold *manifold = *((b2Manifold **)dub_checksdata(L, 2, "b2.Manifold"));
    b2Transform *xfA = *((b2Transform **)dub_checksdata(L, 3, "b2.Transform"));
    float32 radiusA = dub_checknumber(L, 4);
    b2Transform *xfB = *((b2Transform **)dub_checksdata(L, 5, "b2.Transform"));
    float32 radiusB = dub_checknumber(L, 6);
    self->Initialize(manifold, *xfA, radiusA, *xfB, radiusB);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "Initialize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Initialize: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int b2WorldManifold___tostring(lua_State *L) {
  b2WorldManifold *self = *((b2WorldManifold **)dub_checksdata_n(L, 1, "b2.WorldManifold"));
  lua_pushfstring(L, "b2.WorldManifold: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2WorldManifold_member_methods[] = {
  { "__newindex"   , b2WorldManifold__set_ },
  { "__index"      , b2WorldManifold__get_ },
  { "new"          , b2WorldManifold_b2WorldManifold },
  { "points"       , b2WorldManifold_points },
  { "Initialize"   , b2WorldManifold_Initialize },
  { "__tostring"   , b2WorldManifold___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_b2_WorldManifold(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.WorldManifold");
  // <mt>

  // register member methods
  luaL_register(L, NULL, b2WorldManifold_member_methods);
  // save meta-table in b2
  dub_register(L, "b2", "WorldManifold", "WorldManifold");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
